apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: strimzi
  name: custommetric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi
  template:
    metadata:
      labels:
        app: strimzi
    spec:
      containers:
        - name: custommetriccontainer
          image: docker.io/mezzeddine/custommetrics:v0
          ports:
            - containerPort: 8080
              name: brom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demoobservabilitypodmonitor
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      app: strimzi
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - path: /prometheus
      port: brom
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: strimzi
spec:
  replicas: 1
  serviceAccountName: prometheus-server
  podMonitorSelector:
    matchLabels:
      app: strimzi
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  ruleSelector:
    matchLabels:
      role: alert-rules
      app: strimzi
  alerting:
    alertmanagers:
      - namespace: default
        name: alertmanager
        port: alertmanager
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml